apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 3000
      nodePort: 30080  # You can choose any available port between 30000-32767
    - name: https
      port: 443
      targetPort: 443
      nodePort: 30443  # You can choose any available port between 30000-32767
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx


