apiVersion: v1
kind: Service
metadata:
  name: project-1-sparta-app-svc
spec:
  selector:
    app: project-1-sparta-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080  # Ensure this matches the NodePort range
  type: NodePort

